# -*- coding: utf-8 -*-
"""MyfirstPyton

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IQeRjs7HNXL2T0CdWUPIo6Ejp2WYUTDt

2023학년도 응용프로그래밍 화면구현  
파이썬 기초
"""

print("안산공업고등학교");
print("컴퓨터과 3학년 1반 2번 강현묵");
print("파이썬 기초수업");